const QUESTIONS = [
	// ===== EASY =====

	// Python
	{
		id: 'py_snip_001',
		language: 'Python',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'python',
		code: 'def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("world"))',
		hint: '들여쓰기로 블록을 구분하며, f-string으로 문자열 보간을 합니다',
		description: 'Python은 귀도 반 로섬이 1991년 발표한 언어로, 가독성과 생산성을 강조합니다.',
		distractors: ['Ruby', 'CoffeeScript', 'Elixir'],
	},
	{
		id: 'py_snip_002',
		language: 'Python',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'python',
		code: 'numbers = [1, 2, 3, 4, 5]\nsquares = [x ** 2 for x in numbers if x % 2 != 0]\nprint(squares)  # [1, 9, 25]',
		hint: '리스트 컴프리헨션이 특징적인 언어입니다',
		description: 'Python의 리스트 컴프리헨션은 간결하고 가독성 높은 코드를 가능하게 합니다.',
		distractors: ['Haskell', 'Ruby', 'Go'],
	},
	{
		id: 'py_snip_003',
		language: 'Python',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'python',
		code: 'import os\n\nfor root, dirs, files in os.walk("./"):\n    for file in files:\n        print(os.path.join(root, file))',
		hint: 'import로 모듈을 불러오는 인터프리터 언어입니다',
		description: 'Python의 표준 라이브러리는 매우 풍부해 "배터리 포함" 언어라 불립니다.',
		distractors: ['Ruby', 'Perl', 'JavaScript'],
	},
	{
		id: 'py_err_001',
		language: 'Python',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: 'Traceback (most recent call last):\n  File "app.py", line 5, in <module>\n    print(x)\nNameError: name \'x\' is not defined',
		hint: 'Traceback 형식의 에러 메시지를 사용합니다',
		description: 'Python은 Traceback을 통해 에러 발생 경로를 상세히 표시합니다.',
		distractors: ['Ruby', 'Perl', 'CoffeeScript'],
	},
	{
		id: 'py_cmt_001',
		language: 'Python',
		difficulty: 'easy',
		type: 'comment',
		langTag: '',
		code: '# 단일 줄 주석\n\n"""\n여러 줄 문자열로\n주석처럼 사용합니다\n"""',
		hint: '#과 삼중 따옴표를 주석으로 사용합니다',
		description: 'Python은 # 단일 주석과 """를 독스트링/멀티라인 주석으로 활용합니다.',
		distractors: ['Ruby', 'Shell', 'Perl'],
	},

	// JavaScript
	{
		id: 'js_snip_001',
		language: 'JavaScript',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'js',
		code: 'const arr = [1, 2, 3, 4, 5];\nconst result = arr\n  .filter(x => x % 2 === 0)\n  .map(x => x * 10);\nconsole.log(result); // [20, 40]',
		hint: 'console.log와 화살표 함수가 보입니다',
		description: 'JavaScript는 웹 브라우저와 Node.js에서 실행되는 동적 타입 언어입니다.',
		distractors: ['TypeScript', 'CoffeeScript', 'Dart'],
	},
	{
		id: 'js_snip_002',
		language: 'JavaScript',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'js',
		code: 'async function fetchUser(id) {\n  const res = await fetch(`/api/users/${id}`);\n  const data = await res.json();\n  return data;\n}',
		hint: 'async/await와 fetch API를 사용합니다',
		description: 'JavaScript의 async/await는 비동기 코드를 동기적으로 작성할 수 있게 합니다.',
		distractors: ['TypeScript', 'Dart', 'Swift'],
	},
	{
		id: 'js_snip_003',
		language: 'JavaScript',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'js',
		code: 'const { name, age, ...rest } = person;\nconst newArr = [...arr1, ...arr2];\nconst obj = { x, y, z };',
		hint: '구조 분해와 스프레드 연산자가 특징입니다',
		description: 'JavaScript ES6+에서 도입된 구조 분해 할당과 스프레드 연산자입니다.',
		distractors: ['TypeScript', 'CoffeeScript', 'Python'],
	},
	{
		id: 'js_err_001',
		language: 'JavaScript',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: "TypeError: Cannot read properties of undefined (reading 'map')\n    at Array.<anonymous> (app.js:12:18)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
		hint: 'Node.js 스택 트레이스 형식입니다',
		description: 'JavaScript/Node.js의 TypeError는 잘못된 타입에 연산을 시도할 때 발생합니다.',
		distractors: ['TypeScript', 'Java', 'Python'],
	},
	{
		id: 'js_cmt_001',
		language: 'JavaScript',
		difficulty: 'easy',
		type: 'comment',
		langTag: '',
		code: '// 단일 줄 주석\n\n/**\n * JSDoc 주석\n * @param {string} name - 이름\n * @returns {string} 인사말\n */',
		hint: 'JSDoc 형식의 /** */ 주석이 특징입니다',
		description: 'JavaScript는 // 단일 주석, /* */ 블록 주석, /** */ JSDoc 형식을 사용합니다.',
		distractors: ['Java', 'TypeScript', 'PHP'],
	},

	// Java
	{
		id: 'java_snip_001',
		language: 'Java',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'java',
		code: 'public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}',
		hint: 'System.out.println과 public class가 보입니다',
		description: 'Java는 1995년 Sun Microsystems에서 개발한 객체지향 언어로, "한 번 작성, 어디서나 실행"이 특징입니다.',
		distractors: ['Kotlin', 'C#', 'Groovy'],
	},
	{
		id: 'java_snip_002',
		language: 'Java',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'java',
		code: 'import java.util.ArrayList;\nimport java.util.List;\n\nList<String> names = new ArrayList<>();\nnames.add("Alice");\nnames.forEach(System.out::println);',
		hint: 'import java.util와 제네릭 타입, 메서드 참조(::)가 보입니다',
		description: 'Java의 Collections Framework는 List, Map, Set 등 다양한 자료구조를 제공합니다.',
		distractors: ['Kotlin', 'Groovy', 'Scala'],
	},
	{
		id: 'java_err_001',
		language: 'Java',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: 'Exception in thread "main" java.lang.NullPointerException\n    at com.example.App.main(App.java:15)\nCaused by: java.lang.NullPointerException',
		hint: '"Exception in thread" 형식의 에러입니다',
		description: 'Java의 NullPointerException은 null 객체에 메서드를 호출할 때 발생합니다.',
		distractors: ['Kotlin', 'Scala', 'C#'],
	},
	{
		id: 'java_cmt_001',
		language: 'Java',
		difficulty: 'easy',
		type: 'comment',
		langTag: '',
		code: '// 단일 줄 주석\n\n/**\n * Javadoc 주석\n * @author Developer\n * @version 1.0\n * @param args 실행 인자\n */',
		hint: '@author, @version 같은 Javadoc 태그가 보입니다',
		description: 'Java의 Javadoc은 /** */ 형식의 주석으로 API 문서를 자동 생성합니다.',
		distractors: ['JavaScript', 'PHP', 'C++'],
	},

	// C
	{
		id: 'c_snip_001',
		language: 'C',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'c',
		code: '#include <stdio.h>\n\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
		hint: '#include와 printf, return 0이 특징입니다',
		description: 'C는 1972년 Dennis Ritchie가 개발한 시스템 프로그래밍 언어로, 운영체제 개발에 널리 쓰입니다.',
		distractors: ['C++', 'Go', 'Rust'],
	},
	{
		id: 'c_snip_002',
		language: 'C',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'c',
		code: 'int* ptr = malloc(sizeof(int) * 10);\nfor (int i = 0; i < 10; i++) {\n    ptr[i] = i * i;\n}\nfree(ptr);',
		hint: 'malloc/free로 직접 메모리를 관리합니다',
		description: 'C는 포인터와 수동 메모리 관리를 통해 저수준 제어가 가능합니다.',
		distractors: ['C++', 'Rust', 'Assembly'],
	},
	{
		id: 'c_err_001',
		language: 'C',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: 'Segmentation fault (core dumped)\n\nProgram received signal SIGSEGV, Segmentation fault.\n0x0000000000401234 in main ()',
		hint: 'Segmentation fault는 잘못된 메모리 접근 에러입니다',
		description: 'C의 Segmentation Fault는 허용되지 않은 메모리 영역에 접근할 때 발생합니다.',
		distractors: ['C++', 'Rust', 'Assembly'],
	},
	{
		id: 'c_cmt_001',
		language: 'C',
		difficulty: 'easy',
		type: 'comment',
		langTag: '',
		code: '/* 블록 주석\n   여러 줄 사용 가능 */\n\n// C99 이후 지원되는 줄 주석\n\n#include <stdio.h>  /* 헤더 파일 포함 */',
		hint: '/* */ 블록 주석과 #include 지시문이 보입니다',
		description: 'C는 /* */ 블록 주석을 전통적으로 사용하며, C99부터 // 줄 주석도 지원합니다.',
		distractors: ['C++', 'Java', 'PHP'],
	},

	// Go
	{
		id: 'go_snip_001',
		language: 'Go',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'go',
		code: 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}',
		hint: 'package main과 import "fmt", fmt.Println이 특징입니다',
		description: 'Go는 2009년 구글이 개발한 언어로, 단순성과 효율성을 추구합니다.',
		distractors: ['Rust', 'C', 'Swift'],
	},
	{
		id: 'go_snip_002',
		language: 'Go',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'go',
		code: 'func worker(id int, jobs <-chan int, results chan<- int) {\n    for j := range jobs {\n        results <- j * 2\n    }\n}\n\ngo worker(1, jobs, results)',
		hint: 'goroutine(go 키워드)과 채널(<-) 문법이 특징입니다',
		description: 'Go의 goroutine과 channel은 동시성 프로그래밍을 쉽게 만들어줍니다.',
		distractors: ['Rust', 'Erlang', 'Swift'],
	},
	{
		id: 'go_err_001',
		language: 'Go',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: './main.go:8:2: declared and not used: x\n./main.go:12:9: cannot use "hello" (untyped string constant) as int value in assignment',
		hint: '파일명.go 형식의 에러 위치를 표시합니다',
		description: 'Go 컴파일러는 사용하지 않는 변수가 있으면 컴파일을 거부하는 엄격한 언어입니다.',
		distractors: ['Rust', 'C', 'Swift'],
	},
	{
		id: 'go_cmt_001',
		language: 'Go',
		difficulty: 'easy',
		type: 'comment',
		langTag: '',
		code: '// Package main은 실행 가능한 프로그램입니다.\n\n// Println은 표준 출력에 문자열을 출력합니다.\nfunc Println(s string) {\n    // ...\n}',
		hint: '// 형식 주석이 함수/패키지 문서로 사용됩니다',
		description: 'Go는 // 형식의 주석이 패키지/함수 문서로 사용되며, godoc으로 자동 추출됩니다.',
		distractors: ['Rust', 'Java', 'C'],
	},

	// TypeScript
	{
		id: 'ts_snip_001',
		language: 'TypeScript',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'typescript',
		code: 'interface User {\n  id: number;\n  name: string;\n  email?: string;\n}\n\nfunction greet(user: User): string {\n  return `Hello, ${user.name}!`;\n}',
		hint: 'interface와 타입 어노테이션(: number, : string)이 특징입니다',
		description: 'TypeScript는 JavaScript의 슈퍼셋으로, 정적 타입 시스템을 추가한 언어입니다.',
		distractors: ['JavaScript', 'Dart', 'Kotlin'],
	},
	{
		id: 'ts_snip_002',
		language: 'TypeScript',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'typescript',
		code: 'type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };\n\nfunction divide(a: number, b: number): Result<number, string> {\n  if (b === 0) return { ok: false, error: "Division by zero" };\n  return { ok: true, value: a / b };\n}',
		hint: '제네릭 타입 파라미터 <T>와 유니온 타입 |이 보입니다',
		description: 'TypeScript의 제네릭과 유니온 타입으로 타입 안전한 코드를 작성할 수 있습니다.',
		distractors: ['JavaScript', 'Rust', 'Swift'],
	},
	{
		id: 'ts_err_001',
		language: 'TypeScript',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: "error TS2322: Type 'string' is not assignable to type 'number'.\nerror TS2339: Property 'foo' does not exist on type 'Bar'.\n  at src/index.ts:24:5",
		hint: 'TS + 숫자 에러 코드 형식입니다 (ex: TS2322)',
		description: 'TypeScript 컴파일러는 타입 불일치 시 TS 에러 코드와 함께 오류를 표시합니다.',
		distractors: ['JavaScript', 'Java', 'C#'],
	},

	// C++
	{
		id: 'cpp_snip_001',
		language: 'C++',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'cpp',
		code: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}',
		hint: 'std::cout와 << 연산자가 특징입니다',
		description: 'C++은 1983년 비야네 스트롭스트룹이 C에 객체지향을 추가해 만든 언어입니다.',
		distractors: ['C', 'Rust', 'Java'],
	},
	{
		id: 'cpp_snip_002',
		language: 'C++',
		difficulty: 'easy',
		type: 'snippet',
		langTag: 'cpp',
		code: '#include <vector>\n#include <algorithm>\n\nstd::vector<int> nums = {3, 1, 4, 1, 5};\nstd::sort(nums.begin(), nums.end());\nauto it = std::find(nums.begin(), nums.end(), 4);',
		hint: 'std::vector와 auto 키워드, begin()/end() 이터레이터가 보입니다',
		description: 'C++ STL은 vector, sort, find 등 풍부한 컨테이너와 알고리즘을 제공합니다.',
		distractors: ['C', 'Rust', 'Java'],
	},
	{
		id: 'cpp_err_001',
		language: 'C++',
		difficulty: 'easy',
		type: 'error',
		langTag: '',
		code: "error: 'cout' was not declared in this scope\nerror: use of undeclared identifier 'endl'\nnote: did you forget '#include <iostream>'?",
		hint: "scope 에러와 'did you forget' 힌트가 보입니다",
		description: 'C++ 컴파일러는 선언되지 않은 식별자 사용 시 관련 헤더 파일 포함을 제안합니다.',
		distractors: ['C', 'Java', 'Rust'],
	},

	// ===== NORMAL =====

	// Rust
	{
		id: 'rs_snip_001',
		language: 'Rust',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'rust',
		code: 'fn main() {\n    let x: i32 = 5;\n    let y = &x;\n    println!("x = {}, y = {}", x, y);\n}',
		hint: 'let과 & 참조, println! 매크로가 특징입니다',
		description: 'Rust는 2015년 Mozilla가 발표한 언어로, 메모리 안전성을 컴파일 타임에 보장합니다.',
		distractors: ['Go', 'Swift', 'C++'],
	},
	{
		id: 'rs_snip_002',
		language: 'Rust',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'rust',
		code: 'enum Shape {\n    Circle(f64),\n    Rectangle(f64, f64),\n}\n\nfn area(shape: &Shape) -> f64 {\n    match shape {\n        Shape::Circle(r) => std::f64::consts::PI * r * r,\n        Shape::Rectangle(w, h) => w * h,\n    }\n}',
		hint: 'enum과 match 패턴 매칭, f64 타입이 특징입니다',
		description: 'Rust의 enum과 match는 대수적 데이터 타입과 패턴 매칭을 지원합니다.',
		distractors: ['Swift', 'Kotlin', 'Haskell'],
	},
	{
		id: 'rs_snip_003',
		language: 'Rust',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'rust',
		code: 'fn largest<T: PartialOrd>(list: &[T]) -> &T {\n    let mut largest = &list[0];\n    for item in list {\n        if item > largest {\n            largest = item;\n        }\n    }\n    largest\n}',
		hint: '제네릭 트레이트 바운드 <T: PartialOrd>가 특징입니다',
		description: 'Rust의 제네릭과 트레이트 시스템은 타입 안전한 추상화를 제공합니다.',
		distractors: ['Go', 'C++', 'Swift'],
	},
	{
		id: 'rs_err_001',
		language: 'Rust',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: "error[E0382]: borrow of moved value: `s`\n  --> src/main.rs:6:20\n   |\n4  |     let s = String::from(\"hello\");\n5  |     let s2 = s;\n   |              - value moved here\n6  |     println!(\"{}\", s);\n   |                    ^ value borrowed here after move",
		hint: 'error[E숫자] 형식과 borrow checker 에러입니다',
		description: 'Rust의 소유권 시스템은 값이 이동(move)된 후 사용하는 것을 컴파일 타임에 방지합니다.',
		distractors: ['Go', 'C++', 'Swift'],
	},
	{
		id: 'rs_cmt_001',
		language: 'Rust',
		difficulty: 'normal',
		type: 'comment',
		langTag: '',
		code: '/// 문서화 주석 (rustdoc)\n///\n/// # Examples\n/// ```\n/// let x = add(1, 2);\n/// assert_eq!(x, 3);\n/// ```\nfn add(a: i32, b: i32) -> i32 {',
		hint: '/// 형식의 문서화 주석과 # Examples 섹션이 특징입니다',
		description: 'Rust의 /// 주석은 rustdoc으로 문서를 자동 생성하며, 코드 예제 테스트도 가능합니다.',
		distractors: ['Go', 'Swift', 'C++'],
	},

	// Swift
	{
		id: 'swift_snip_001',
		language: 'Swift',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'swift',
		code: 'let name: String = "World"\nvar count = 0\n\nif let unwrapped = optionalValue {\n    print("Value: \\(unwrapped)")\n} else {\n    print("No value")\n}',
		hint: 'if let 옵셔널 바인딩과 \\() 문자열 보간이 특징입니다',
		description: 'Swift는 Apple이 2014년 발표한 언어로, 옵셔널 타입과 안전한 메모리 관리가 특징입니다.',
		distractors: ['Kotlin', 'Dart', 'Go'],
	},
	{
		id: 'swift_snip_002',
		language: 'Swift',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'swift',
		code: 'struct Point {\n    var x: Double\n    var y: Double\n}\n\nextension Point {\n    func distance(to other: Point) -> Double {\n        return sqrt((x - other.x) * (x - other.x) + (y - other.y) * (y - other.y))\n    }\n}',
		hint: 'struct와 extension 키워드, 매개변수 레이블(to:)이 특징입니다',
		description: 'Swift의 extension은 기존 타입에 메서드를 추가할 수 있게 합니다.',
		distractors: ['Kotlin', 'Dart', 'Rust'],
	},
	{
		id: 'swift_err_001',
		language: 'Swift',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: "error: value of optional type 'String?' must be unwrapped to a value of type 'String'\nnote: coalesce using '??' to provide a default when the optional value contains 'nil'\nnote: force-unwrap using '!' to abort execution if the optional value contains 'nil'",
		hint: "옵셔널 관련 에러로 '??' 와 '!'를 제안합니다",
		description: 'Swift의 옵셔널 시스템은 nil 값을 명시적으로 다루도록 강제합니다.',
		distractors: ['Kotlin', 'Dart', 'Go'],
	},

	// Kotlin
	{
		id: 'kt_snip_001',
		language: 'Kotlin',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'kotlin',
		code: 'data class User(\n    val id: Int,\n    val name: String,\n    val email: String? = null\n)\n\nfun main() {\n    val user = User(1, "Alice")\n    println(user.copy(name = "Bob"))\n}',
		hint: 'data class와 val, copy() 메서드가 특징입니다',
		description: 'Kotlin의 data class는 equals, hashCode, copy 등을 자동으로 생성합니다.',
		distractors: ['Java', 'Scala', 'Swift'],
	},
	{
		id: 'kt_snip_002',
		language: 'Kotlin',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'kotlin',
		code: 'val numbers = listOf(1, 2, 3, 4, 5)\nval result = numbers\n    .filter { it % 2 == 0 }\n    .map { it * it }\n    .sum()\nprintln(result)  // 20',
		hint: '{ it } 람다로 단일 파라미터를 표현합니다',
		description: 'Kotlin은 it 키워드를 사용해 람다의 단일 파라미터를 간결하게 표현합니다.',
		distractors: ['Java', 'Scala', 'Groovy'],
	},
	{
		id: 'kt_snip_003',
		language: 'Kotlin',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'kotlin',
		code: 'val str: String? = null\nval length = str?.length ?: 0\n\nwhen (length) {\n    0 -> println("비어있음")\n    in 1..10 -> println("짧음")\n    else -> println("긺")\n}',
		hint: '?. 안전 호출, ?: 엘비스 연산자, when 표현식이 특징입니다',
		description: 'Kotlin의 안전 호출 연산자(?.)와 엘비스 연산자(?:)로 null 처리를 간결하게 합니다.',
		distractors: ['Swift', 'Java', 'Scala'],
	},
	{
		id: 'kt_err_001',
		language: 'Kotlin',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: 'error: type mismatch: inferred type is String? but String was expected\nerror: only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?',
		hint: "nullable 타입 관련 에러로 '?.' 또는 '!!.'을 제안합니다",
		description: 'Kotlin의 타입 시스템은 null 가능 타입(T?)과 non-null 타입(T)을 엄격히 구분합니다.',
		distractors: ['Swift', 'Java', 'Dart'],
	},

	// Ruby
	{
		id: 'rb_snip_001',
		language: 'Ruby',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'ruby',
		code: 'def greet(name)\n  "Hello, #{name}!"\nend\n\nnames = ["Alice", "Bob", "Charlie"]\nnames.each do |name|\n  puts greet(name)\nend',
		hint: '#{} 보간, do..end 블록, def..end가 특징입니다',
		description: 'Ruby는 1995년 마츠모토 유키히로가 개발한 언어로, 개발자의 행복을 최우선으로 합니다.',
		distractors: ['Python', 'Elixir', 'CoffeeScript'],
	},
	{
		id: 'rb_snip_002',
		language: 'Ruby',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'ruby',
		code: 'class Animal\n  attr_accessor :name, :age\n\n  def initialize(name, age)\n    @name = name\n    @age = age\n  end\n\n  def to_s\n    "#{@name} (#{@age}살)"\n  end\nend',
		hint: 'attr_accessor와 @인스턴스 변수, initialize가 특징입니다',
		description: 'Ruby의 attr_accessor는 인스턴스 변수의 getter/setter를 자동으로 생성합니다.',
		distractors: ['Python', 'Elixir', 'Groovy'],
	},
	{
		id: 'rb_err_001',
		language: 'Ruby',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: "NoMethodError: undefined method 'upcase' for nil:NilClass\n    from app.rb:12:in 'greet'\n    from app.rb:18:in '<main>'",
		hint: 'NilClass에서 발생한 NoMethodError 형식입니다',
		description: 'Ruby의 NoMethodError는 nil에 메서드를 호출할 때 발생하며, NilClass를 명시합니다.',
		distractors: ['Python', 'Elixir', 'PHP'],
	},
	{
		id: 'rb_cmt_001',
		language: 'Ruby',
		difficulty: 'normal',
		type: 'comment',
		langTag: '',
		code: '# 단일 줄 주석\n\n=begin\n여러 줄 주석\n이렇게 사용합니다\n=end\n\n# frozen_string_literal: true',
		hint: '=begin...=end 형식의 멀티라인 주석이 특징입니다',
		description: 'Ruby는 # 단일 주석과 =begin...=end 블록 주석을 사용합니다.',
		distractors: ['Python', 'Perl', 'Shell'],
	},

	// PHP
	{
		id: 'php_snip_001',
		language: 'PHP',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'php',
		code: '<?php\n$name = "World";\n$age = 25;\n\necho "Hello, {$name}! Age: {$age}\\n";\n\n$arr = ["a" => 1, "b" => 2];\nforeach ($arr as $key => $val) {\n    echo "$key: $val\\n";\n}',
		hint: '<?php 태그와 $ 변수 접두사, echo가 특징입니다',
		description: 'PHP는 1994년 개발된 서버사이드 스크립트 언어로, 웹 개발에 광범위하게 사용됩니다.',
		distractors: ['Ruby', 'Perl', 'Python'],
	},
	{
		id: 'php_snip_002',
		language: 'PHP',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'php',
		code: '<?php\nclass User {\n    private string $name;\n\n    public function __construct(string $name) {\n        $this->name = $name;\n    }\n\n    public function greet(): string {\n        return "Hello, {$this->name}!";\n    }\n}',
		hint: '$this 포인터와 __construct 생성자가 특징입니다',
		description: 'PHP의 클래스는 __construct 생성자와 $this로 인스턴스를 참조합니다.',
		distractors: ['Ruby', 'Python', 'Perl'],
	},
	{
		id: 'php_err_001',
		language: 'PHP',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: 'Fatal error: Uncaught TypeError: Argument 1 passed to greet() must be of the type string, int given\n  in /var/www/html/index.php:15\nStack trace:\n#0 /var/www/html/index.php(22): greet(42)',
		hint: 'Fatal error로 시작하며 /var/www/html 경로가 보입니다',
		description: 'PHP의 Fatal error는 복구 불가능한 에러로, 주로 타입 불일치나 메모리 초과 시 발생합니다.',
		distractors: ['Ruby', 'Python', 'Perl'],
	},

	// Scala
	{
		id: 'scala_snip_001',
		language: 'Scala',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'scala',
		code: 'case class Person(name: String, age: Int)\n\nobject Main extends App {\n  val people = List(Person("Alice", 30), Person("Bob", 25))\n  val sorted = people.sortBy(_.age)\n  sorted.foreach(p => println(s"${p.name}: ${p.age}"))\n}',
		hint: 'case class와 object Main extends App, s"" 문자열이 특징입니다',
		description: 'Scala는 JVM에서 실행되는 함수형+객체지향 혼합 언어로, case class로 불변 데이터를 표현합니다.',
		distractors: ['Kotlin', 'Java', 'Groovy'],
	},
	{
		id: 'scala_snip_002',
		language: 'Scala',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'scala',
		code: 'def factorial(n: Int): BigInt = n match {\n  case 0 => 1\n  case n => n * factorial(n - 1)\n}\n\nval result = (1 to 10).map(factorial).toList',
		hint: 'match/case 패턴 매칭과 BigInt 타입이 특징입니다',
		description: 'Scala의 패턴 매칭은 강력한 분기 처리를 가능하게 하며, 재귀를 자연스럽게 표현합니다.',
		distractors: ['Haskell', 'Kotlin', 'Clojure'],
	},
	{
		id: 'scala_err_001',
		language: 'Scala',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: '[error] /src/main/scala/App.scala:8:12: type mismatch;\n[error]  found   : Int(42)\n[error]  required: String\n[error]     val s: String = 42',
		hint: '[error] 형식의 컴파일 에러와 .scala 파일명이 보입니다',
		description: 'Scala 컴파일러는 타입 불일치 시 found/required 형식으로 상세한 에러를 표시합니다.',
		distractors: ['Kotlin', 'Java', 'Haskell'],
	},

	// Dart
	{
		id: 'dart_snip_001',
		language: 'Dart',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'dart',
		code: 'void main() {\n  String? name = null;\n  int count = name?.length ?? 0;\n\n  final list = <int>[1, 2, 3];\n  list.forEach((item) => print(item));\n}',
		hint: 'String? null-safety와 final, <int>[] 제네릭이 특징입니다',
		description: 'Dart는 Google이 개발한 언어로, Flutter 앱 개발에 주로 사용되며 강한 타입 시스템을 가집니다.',
		distractors: ['Kotlin', 'Swift', 'TypeScript'],
	},
	{
		id: 'dart_snip_002',
		language: 'Dart',
		difficulty: 'normal',
		type: 'snippet',
		langTag: 'dart',
		code: 'class Animal {\n  final String name;\n  Animal(this.name);\n\n  void speak() => print(\'$name makes a sound\');\n}\n\nclass Dog extends Animal {\n  Dog(String name) : super(name);\n\n  @override\n  void speak() => print(\'$name barks!\');\n}',
		hint: 'this.name 생성자 단축과 : super() 초기화 리스트가 특징입니다',
		description: 'Dart의 this.parameter 생성자 문법은 Flutter에서 자주 볼 수 있는 패턴입니다.',
		distractors: ['Swift', 'Kotlin', 'Java'],
	},
	{
		id: 'dart_err_001',
		language: 'Dart',
		difficulty: 'normal',
		type: 'error',
		langTag: '',
		code: "Error: A value of type 'String?' can't be assigned to a variable of type 'String' because 'String?' is nullable and 'String' is not.\n - 'String' is from 'dart:core'.",
		hint: "dart:core를 언급하며 nullable 타입 에러를 표시합니다",
		description: 'Dart의 null safety는 String?과 String을 구분하여 null 관련 런타임 에러를 방지합니다.',
		distractors: ['Kotlin', 'Swift', 'TypeScript'],
	},

	// ===== HARD =====

	// Haskell
	{
		id: 'hs_snip_001',
		language: 'Haskell',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'haskell',
		code: 'factorial :: Integer -> Integer\nfactorial 0 = 1\nfactorial n = n * factorial (n - 1)\n\nmain :: IO ()\nmain = print (factorial 10)',
		hint: '타입 시그니처(::)와 패턴 매칭 기반 함수 정의가 특징입니다',
		description: 'Haskell은 1990년 발표된 순수 함수형 언어로, 지연 평가(lazy evaluation)와 강한 타입 시스템이 특징입니다.',
		distractors: ['Elm', 'OCaml', 'Erlang'],
	},
	{
		id: 'hs_snip_002',
		language: 'Haskell',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'haskell',
		code: 'import Data.List (sort, nub)\n\nquicksort :: Ord a => [a] -> [a]\nquicksort [] = []\nquicksort (x:xs) = quicksort smaller ++ [x] ++ quicksort larger\n  where\n    smaller = [y | y <- xs, y <= x]\n    larger  = [y | y <- xs, y > x]',
		hint: '리스트 컴프리헨션 [y | y <- xs]과 where 절이 특징입니다',
		description: 'Haskell의 리스트 컴프리헨션과 패턴 매칭으로 퀵소트를 간결하게 표현할 수 있습니다.',
		distractors: ['OCaml', 'Clojure', 'Erlang'],
	},
	{
		id: 'hs_snip_003',
		language: 'Haskell',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'haskell',
		code: 'data Tree a = Leaf | Node (Tree a) a (Tree a)\n\ninsert :: Ord a => a -> Tree a -> Tree a\ninsert x Leaf = Node Leaf x Leaf\ninsert x (Node l v r)\n  | x < v    = Node (insert x l) v r\n  | x > v    = Node l v (insert x r)\n  | otherwise = Node l v r',
		hint: 'data 키워드로 대수적 데이터 타입을 정의합니다',
		description: 'Haskell의 대수적 데이터 타입(ADT)으로 트리 자료구조를 간결하게 표현합니다.',
		distractors: ['OCaml', 'Elm', 'Scala'],
	},
	{
		id: 'hs_err_001',
		language: 'Haskell',
		difficulty: 'hard',
		type: 'error',
		langTag: '',
		code: "app.hs:5:12: error:\n    • Couldn't match expected type 'Int' with actual type 'Bool'\n    • In the expression: True\n      In an equation for 'foo': foo = True",
		hint: "Couldn't match expected type 형식의 타입 에러입니다",
		description: 'Haskell의 강한 타입 시스템은 타입 불일치를 컴파일 타임에 정확히 잡아냅니다.',
		distractors: ['OCaml', 'Elm', 'Rust'],
	},

	// Erlang
	{
		id: 'erl_snip_001',
		language: 'Erlang',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'erlang',
		code: '-module(hello).\n-export([greet/1]).\n\ngreet(Name) ->\n    io:format("Hello, ~s!~n", [Name]).\n\nstart() ->\n    spawn(fun() -> greet("World") end).',
		hint: '-module과 -export 지시어, -> 함수 정의가 특징입니다',
		description: 'Erlang은 Ericsson이 1987년 개발한 언어로, 분산 시스템과 고가용성에 특화되어 있습니다.',
		distractors: ['Elixir', 'Haskell', 'Prolog'],
	},
	{
		id: 'erl_snip_002',
		language: 'Erlang',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'erlang',
		code: 'factorial(0) -> 1;\nfactorial(N) when N > 0 ->\n    N * factorial(N - 1).\n\nloop() ->\n    receive\n        {From, Msg} ->\n            From ! {self(), Msg},\n            loop()\n    end.',
		hint: 'receive...end 메시지 수신과 ! 메시지 전송이 특징입니다',
		description: 'Erlang의 액터 모델은 프로세스 간 메시지 패싱으로 동시성을 구현합니다.',
		distractors: ['Elixir', 'Go', 'Haskell'],
	},
	{
		id: 'erl_err_001',
		language: 'Erlang',
		difficulty: 'hard',
		type: 'error',
		langTag: '',
		code: '** exception error: no match of right hand side value 42\n   in function  hello:start/0 (hello.erl, line 8)\n   in call from shell:evaluator/3',
		hint: '** exception error: no match 형식의 에러입니다',
		description: 'Erlang의 패턴 매칭 실패는 "no match of right hand side value" 에러를 발생시킵니다.',
		distractors: ['Elixir', 'Haskell', 'Prolog'],
	},

	// Prolog
	{
		id: 'pro_snip_001',
		language: 'Prolog',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'prolog',
		code: 'parent(tom, bob).\nparent(tom, liz).\nparent(bob, ann).\n\ngrandparent(X, Z) :-\n    parent(X, Y),\n    parent(Y, Z).\n\n?- grandparent(tom, ann).\n% true',
		hint: ':- 규칙과 사실(fact) 기반 선언형 문법이 특징입니다',
		description: 'Prolog는 논리 프로그래밍 언어로, 사실과 규칙을 선언하면 자동으로 추론합니다.',
		distractors: ['Erlang', 'Haskell', 'Lisp'],
	},
	{
		id: 'pro_snip_002',
		language: 'Prolog',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'prolog',
		code: 'factorial(0, 1) :- !.\nfactorial(N, F) :-\n    N > 0,\n    N1 is N - 1,\n    factorial(N1, F1),\n    F is N * F1.',
		hint: 'is 산술 연산자와 ! 컷 연산자가 특징입니다',
		description: 'Prolog의 is 연산자는 오른쪽 수식을 평가해 왼쪽 변수에 단일화합니다.',
		distractors: ['Erlang', 'Mercury', 'Haskell'],
	},

	// COBOL
	{
		id: 'cob_snip_001',
		language: 'COBOL',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'cobol',
		code: 'IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO-WORLD.\n\nPROCEDURE DIVISION.\n    DISPLAY "Hello, World!"\n    STOP RUN.',
		hint: 'IDENTIFICATION DIVISION과 PROCEDURE DIVISION이 특징입니다',
		description: 'COBOL은 1959년 개발된 언어로, 금융·행정 분야 레거시 시스템에 여전히 광범위하게 사용됩니다.',
		distractors: ['Fortran', 'RPG', 'PL/I'],
	},
	{
		id: 'cob_snip_002',
		language: 'COBOL',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'cobol',
		code: 'DATA DIVISION.\nWORKING-STORAGE SECTION.\n01  WS-NUM1    PIC 9(4) VALUE 1000.\n01  WS-NUM2    PIC 9(4) VALUE 2000.\n01  WS-RESULT  PIC 9(5).\n\nPROCEDURE DIVISION.\n    ADD WS-NUM1 TO WS-NUM2 GIVING WS-RESULT\n    DISPLAY WS-RESULT.',
		hint: 'PIC 9(4) 그림절과 ADD...GIVING 문법이 특징입니다',
		description: 'COBOL의 PIC(Picture) 절은 데이터 형식을 명시하며, 금융 계산에 정밀도가 높습니다.',
		distractors: ['Fortran', 'PL/I', 'RPG'],
	},

	// Lisp
	{
		id: 'lisp_snip_001',
		language: 'Lisp',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'lisp',
		code: '(defun factorial (n)\n  (if (= n 0)\n      1\n      (* n (factorial (- n 1)))))\n\n(print (factorial 10))',
		hint: 'defun과 괄호 중첩 기반 전위 표기법이 특징입니다',
		description: 'Lisp(List Processing)은 1958년 개발된 언어로, 모든 코드가 리스트로 표현되는 동형성이 특징입니다.',
		distractors: ['Scheme', 'Clojure', 'Haskell'],
	},
	{
		id: 'lisp_snip_002',
		language: 'Lisp',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'lisp',
		code: "(setq numbers '(1 2 3 4 5))\n(mapcar (lambda (x) (* x x)) numbers)\n; => (1 4 9 16 25)\n\n(let ((x 10)\n      (y 20))\n  (+ x y))",
		hint: "setq, mapcar, lambda, let이 모두 등장하는 언어입니다",
		description: 'Common Lisp의 mapcar는 리스트의 각 원소에 함수를 적용하는 고차 함수입니다.',
		distractors: ['Scheme', 'Racket', 'Clojure'],
	},

	// Scheme
	{
		id: 'scm_snip_001',
		language: 'Scheme',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'scheme',
		code: '(define (factorial n)\n  (if (= n 0) 1\n      (* n (factorial (- n 1)))))\n\n(display (factorial 10))\n(newline)',
		hint: 'define과 display/newline이 Lisp 계열 중에서도 특징적입니다',
		description: 'Scheme은 1975년 MIT에서 개발된 Lisp 방언으로, 간결한 문법과 꼬리 재귀 최적화가 특징입니다.',
		distractors: ['Lisp', 'Racket', 'Clojure'],
	},
	{
		id: 'scm_snip_002',
		language: 'Scheme',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'scheme',
		code: '(define (make-counter)\n  (let ((count 0))\n    (lambda ()\n      (set! count (+ count 1))\n      count)))\n\n(define counter (make-counter))\n(counter) ; => 1\n(counter) ; => 2',
		hint: 'let과 lambda, set!으로 클로저를 구현하는 패턴입니다',
		description: 'Scheme의 클로저는 렉시컬 스코프와 일급 함수를 이용해 상태를 캡슐화합니다.',
		distractors: ['Lisp', 'Clojure', 'Haskell'],
	},

	// Fortran
	{
		id: 'ftn_snip_001',
		language: 'Fortran',
		difficulty: 'hard',
		type: 'snippet',
		langTag: 'fortran',
		code: 'PROGRAM HelloWorld\n  IMPLICIT NONE\n  INTEGER :: i\n  REAL :: sum\n\n  sum = 0.0\n  DO i = 1, 100\n    sum = sum + i\n  END DO\n\n  PRINT *, "Sum =", sum\nEND PROGRAM HelloWorld',
		hint: 'PROGRAM...END PROGRAM과 DO 루프, IMPLICIT NONE이 특징입니다',
		description: 'Fortran은 1957년 IBM이 개발한 최초의 고급 언어로, 수치 계산 분야에서 여전히 사용됩니다.',
		distractors: ['COBOL', 'Pascal', 'PL/I'],
	},

	// ===== EXPERT =====

	// APL
	{
		id: 'apl_snip_001',
		language: 'APL',
		difficulty: 'expert',
		type: 'snippet',
		langTag: '',
		code: '⍝ 팩토리얼\n×/⍳10\n⍝ 결과: 3628800\n\n⍝ 소수 판별\n(~R∊R∘.×R)/R←1↓⍳20',
		hint: '⍝ 주석, ⍳ 이오타, ⌹ 같은 특수 기호가 특징입니다',
		description: 'APL(A Programming Language)은 1966년 개발된 배열 언어로, 수학 기호를 그대로 문법에 활용합니다.',
		distractors: ['J', 'K', 'BQN'],
	},
	{
		id: 'apl_snip_002',
		language: 'APL',
		difficulty: 'expert',
		type: 'snippet',
		langTag: '',
		code: '⊢ life ← {↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}',
		hint: '단 한 줄로 Conway의 Life Game을 구현한 언어입니다',
		description: 'APL은 극도로 간결한 표현이 가능해, 복잡한 알고리즘을 단 한 줄로 작성할 수 있습니다.',
		distractors: ['J', 'K', 'BQN'],
	},

	// Forth
	{
		id: 'forth_snip_001',
		language: 'Forth',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'forth',
		code: ': FACTORIAL\n  DUP 0= IF DROP 1 EXIT THEN\n  DUP 1- FACTORIAL * ;\n\n10 FACTORIAL .\n\\ 결과: 3628800',
		hint: '스택 기반 RPN과 : ... ; 단어 정의가 특징입니다',
		description: 'Forth는 1970년 개발된 스택 기반 언어로, 역폴란드 표기법(RPN)으로 연산합니다.',
		distractors: ['PostScript', 'Factor', 'Joy'],
	},
	{
		id: 'forth_snip_002',
		language: 'Forth',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'forth',
		code: ': SQUARE DUP * ;\n: CUBE DUP SQUARE * ;\n\n5 SQUARE .   \\ 25\n3 CUBE .     \\ 27\n\n\\ 스택 조작\n10 20 SWAP .  \\ 10\n1 2 3 ROT .   \\ 1',
		hint: 'DUP, SWAP, ROT 같은 스택 조작 단어가 특징입니다',
		description: 'Forth의 DUP, SWAP, ROT 등은 스택을 직접 조작하는 기본 단어(word)입니다.',
		distractors: ['PostScript', 'Factor', 'Assembly'],
	},

	// Assembly (x86)
	{
		id: 'asm_snip_001',
		language: 'Assembly',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'asm',
		code: 'section .data\n    msg db "Hello, World!", 0x0a\n    len equ $ - msg\n\nsection .text\n    global _start\n_start:\n    mov eax, 4\n    mov ebx, 1\n    mov ecx, msg\n    mov edx, len\n    int 0x80',
		hint: 'mov, int 0x80 시스템 콜과 section .data/.text가 특징입니다',
		description: 'x86 어셈블리는 레지스터(eax, ebx)와 시스템 콜(int 0x80)로 직접 CPU를 제어합니다.',
		distractors: ['C', 'Forth', 'MIPS'],
	},
	{
		id: 'asm_snip_002',
		language: 'Assembly',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'asm',
		code: 'factorial:\n    cmp rdi, 0\n    je  .base\n    push rdi\n    dec rdi\n    call factorial\n    pop rdi\n    imul rax, rdi\n    ret\n.base:\n    mov rax, 1\n    ret',
		hint: 'cmp, je, push/pop, call/ret 명령어가 특징입니다',
		description: 'x86-64 어셈블리에서 재귀는 스택(push/pop)과 call/ret 명령어로 구현합니다.',
		distractors: ['C', 'Forth', 'MIPS'],
	},

	// J
	{
		id: 'j_snip_001',
		language: 'J',
		difficulty: 'expert',
		type: 'snippet',
		langTag: '',
		code: 'NB. J 언어 팩토리얼\n!10\nNB. 결과: 3628800\n\nNB. 퀵소트\nqs=: (($:@(<#[), (=#[), $:@(>#[)) ({~ ?@#)) ^: (1 < #)',
		hint: 'NB. 주석과 =: 할당, ^: 반복 연산자가 특징입니다',
		description: 'J는 APL에서 파생된 배열 처리 언어로, ASCII 문자만 사용하며 강력한 암묵 프로그래밍을 지원합니다.',
		distractors: ['APL', 'K', 'BQN'],
	},

	// Smalltalk
	{
		id: 'st_snip_001',
		language: 'Smalltalk',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'smalltalk',
		code: "| counter |\ncounter := 0.\n1 to: 10 do: [:i |\n    counter := counter + i.\n].\nTranscript showCr: counter printString.",
		hint: '| 변수 선언, := 할당, [:i | ] 블록 문법이 특징입니다',
		description: 'Smalltalk는 1972년 Xerox PARC에서 개발된 순수 객체지향 언어로, GUI 환경의 시초입니다.',
		distractors: ['Ruby', 'Pharo', 'Self'],
	},
	{
		id: 'st_snip_002',
		language: 'Smalltalk',
		difficulty: 'expert',
		type: 'snippet',
		langTag: 'smalltalk',
		code: "Object subclass: #Animal\n    instanceVariableNames: 'name'\n    classVariableNames: ''\n    poolDictionaries: ''\n    category: 'Example'.\n\nAnimal >> speak [\n    ^'...' \n]",
		hint: 'subclass: #ClassName과 >> 메서드 정의가 특징입니다',
		description: 'Smalltalk에서 모든 것은 객체이며, 클래스 정의부터 숫자 연산까지 메시지 전송으로 동작합니다.',
		distractors: ['Ruby', 'Self', 'Pharo'],
	},

	// Lisp error
	{
		id: 'lisp_err_001',
		language: 'Lisp',
		difficulty: 'expert',
		type: 'error',
		langTag: '',
		code: '; COMMON-LISP error:\n; Unbound variable: FOO\n;    [Condition of type UNBOUND-VARIABLE]\n;\n; Restarts:\n;  0: [CONTINUE] Retry using FOO.',
		hint: 'Condition of type UNBOUND-VARIABLE 형식의 에러입니다',
		description: 'Common Lisp의 조건 시스템(condition system)은 에러를 유연하게 처리할 수 있는 restart 메커니즘을 제공합니다.',
		distractors: ['Scheme', 'Clojure', 'Racket'],
	},

	// ===== BONUS =====

	// Brainfuck
	{
		id: 'bf_snip_001',
		language: 'Brainfuck',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: '++++++++++\n[>+++++++>++++++++++>+++>+<<<<-]\n>++.>+.+++++++..+++.\n>++.<<+++++++++++++++.\n>.+++.------.--------.\n>+.>.',
		hint: '+, -, >, <, [, ], ., , 8개 명령어만 사용합니다',
		description: 'Brainfuck은 1993년 Urban Müller가 만든 난해한 언어(Esolang)로, 최소한의 명령어로 "Hello World"를 출력하는 코드입니다.',
		distractors: ['Whitespace', 'Ook!', 'Malbolge'],
	},
	{
		id: 'bf_snip_002',
		language: 'Brainfuck',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: '>>++++[<++++[<++++>-]>-]<<.\n>+++++++++++++++++++++++++++++++.\n---.\n+.\n+++++++.\n.\n+++.\n[-]>++++++++[<++++++++>-]<.\n>++++++++++++++++++++++++++++++++++.\n---.\n+.\n+++++++.\n.',
		hint: '모든 코드가 +, -, >, <, [, ], ., , 으로만 구성됩니다',
		description: 'Brainfuck은 메모리 포인터(>/<)와 증감(+/-), 루프([])만으로 튜링 완전 언어를 구현했습니다.',
		distractors: ['Whitespace', 'Ook!', 'Malbolge'],
	},

	// Whitespace
	{
		id: 'ws_snip_001',
		language: 'Whitespace',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: '[공백][공백][탭][개행]\n[공백][탭][공백][공백][개행]\n[탭][개행][공백][공백]\n\n(실제 코드는 공백·탭·개행 문자만으로 구성됩니다)\n(여기서 눈에 보이는 설명은 시각화한 것입니다)',
		hint: '공백(Space), 탭(Tab), 개행(LF) 문자만으로 동작합니다',
		description: 'Whitespace는 2003년 공개된 Esolang으로, 공백·탭·개행 3가지 문자만이 유효한 명령이고 나머지는 무시됩니다.',
		distractors: ['Brainfuck', 'Malbolge', 'Ook!'],
	},

	// Malbolge
	{
		id: 'mal_snip_001',
		language: 'Malbolge',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: "(=<`#9]~6ZY32Vx/4Rs+0No-&Jk)\"Fh}|Bcy?`=*z]Kw%oG4UUS0/@-ejc(:'8dc",
		hint: '의도적으로 프로그래밍이 극도로 어렵게 설계된 언어입니다',
		description: 'Malbolge는 1998년 Ben Olmstead가 만든 언어로, "Hello World" 출력 프로그램을 발견하는 데만 2년이 걸렸습니다.',
		distractors: ['Brainfuck', 'Whitespace', 'INTERCAL'],
	},

	// Ook!
	{
		id: 'ook_snip_001',
		language: 'Ook!',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: 'Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook. Ook. Ook.\nOok? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook.\nOok? Ook! Ook. Ook! Ook? Ook. Ook.',
		hint: 'Ook., Ook?, Ook! 세 가지 기호 조합만으로 동작합니다',
		description: 'Ook!은 Brainfuck을 오랑우탄 언어로 변환한 Esolang으로, Ook., Ook?, Ook! 세 토큰으로 8가지 명령을 표현합니다.',
		distractors: ['Brainfuck', 'Whitespace', 'Chef'],
	},

	// LOLCODE
	{
		id: 'lol_snip_001',
		language: 'LOLCODE',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: 'HAI 1.2\n  CAN HAS STDIO?\n  VISIBLE "HAI WRLD!"\n  I HAS A VAR ITZ 0\n  IM IN YR LOOP UPPIN YR VAR TIL BOTH SAEM VAR AN 10\n    VISIBLE VAR\n  IM OUTTA YR LOOP\nKTHXBYE',
		hint: 'HAI...KTHXBYE와 VISIBLE, IM IN YR LOOP이 특징입니다',
		description: 'LOLCODE는 2007년 인터넷 밈 lolcat 말투로 만든 Esolang으로, HAI(Hi!)로 시작해 KTHXBYE(OK Thanks Bye)로 끝납니다.',
		distractors: ['Brainfuck', 'Chef', 'HQ9+'],
	},

	// Chef
	{
		id: 'chef_snip_001',
		language: 'Chef',
		difficulty: 'bonus',
		type: 'snippet',
		langTag: '',
		code: 'Hello World Souffle.\n\nIngredients.\n72 g haricot beans\n101 eggs\n108 g lard\n\nMethod.\nPut haricot beans into the mixing bowl.\nPut eggs into the mixing bowl.\nLiquify contents of the mixing bowl.\nPour contents of the mixing bowl into the baking dish.',
		hint: '요리 레시피 형식으로 작성하는 언어입니다',
		description: 'Chef는 2002년 David Morgan-Mar가 만든 Esolang으로, 프로그램 코드가 실제 요리 레시피처럼 보이도록 설계됐습니다.',
		distractors: ['Brainfuck', 'LOLCODE', 'Ook!'],
	},
];

module.exports = { QUESTIONS };
