const LOGOS = [
	// ══════════════════════════════════════════════════════════════
	// 🖥️ FRONTEND
	// ══════════════════════════════════════════════════════════════

	// ─── Easy ───────────────────────────────────────────────────
	{
		id: 'logo_react',
		name: 'React',
		category: 'frontend',
		difficulty: 'easy',
		file: 'React.png',
		description: 'Meta(구 Facebook)가 만든 UI 라이브러리. 컴포넌트와 가상 DOM이 핵심입니다.',
		distractors: ['Vue.js', 'Angular', 'Svelte'],
	},
	{
		id: 'logo_vue',
		name: 'Vue.js',
		category: 'frontend',
		difficulty: 'easy',
		file: 'Vue.js.png',
		description: 'Evan You가 만든 프로그레시브 프레임워크. 배우기 쉽고 점진적 도입이 가능합니다.',
		distractors: ['React', 'Angular', 'Nuxt.js'],
	},
	{
		id: 'logo_angular',
		name: 'Angular',
		category: 'frontend',
		difficulty: 'easy',
		file: 'Angular.png',
		description: 'Google이 만든 TypeScript 기반 풀프레임워크. 엔터프라이즈 앱에 주로 쓰입니다.',
		distractors: ['React', 'Vue.js', 'AngularJS'],
	},
	{
		id: 'logo_bootstrap',
		name: 'Bootstrap',
		category: 'frontend',
		difficulty: 'easy',
		file: 'Bootstrap.png',
		description: 'Twitter가 만든 CSS 프레임워크. 반응형 레이아웃을 빠르게 구성할 수 있습니다.',
		distractors: ['Tailwind CSS', 'Bulma', 'Foundation'],
	},

	// ─── Normal ─────────────────────────────────────────────────
	{
		id: 'logo_svelte',
		name: 'Svelte',
		category: 'frontend',
		difficulty: 'normal',
		file: 'Svelte.png',
		description: '컴파일 타임에 코드를 최적화하는 프레임워크. 런타임 오버헤드가 없습니다.',
		distractors: ['React', 'Vue.js', 'Solid.js'],
	},
	{
		id: 'logo_nextjs',
		name: 'Next.js',
		category: 'frontend',
		difficulty: 'normal',
		file: 'Next.js.png',
		description: 'Vercel이 만든 React 기반 풀스택 프레임워크. SSR과 SSG를 모두 지원합니다.',
		distractors: ['Nuxt.js', 'Gatsby', 'Astro'],
	},
	{
		id: 'logo_vite',
		name: 'Vite',
		category: 'frontend',
		difficulty: 'normal',
		file: 'Vite.png',
		description: 'Evan You가 만든 차세대 프론트엔드 빌드 도구. ES Module 기반으로 매우 빠릅니다.',
		distractors: ['Webpack', 'Rollup.js', 'Parcel'],
	},
	{
		id: 'logo_webpack',
		name: 'Webpack',
		category: 'frontend',
		difficulty: 'normal',
		file: 'Webpack.png',
		description: '가장 널리 쓰이는 JS 번들러. 복잡한 모듈 의존성을 하나의 번들로 묶습니다.',
		distractors: ['Vite', 'Rollup.js', 'Parcel'],
	},
	{
		id: 'logo_typescript',
		name: 'TypeScript',
		category: 'frontend',
		difficulty: 'normal',
		file: 'TypeScript.png',
		description: 'Microsoft가 만든 JavaScript 슈퍼셋. 정적 타입 시스템으로 대규모 개발을 지원합니다.',
		distractors: ['JavaScript', 'Babel', 'Flow'],
	},
	{
		id: 'logo_tailwind',
		name: 'Tailwind CSS',
		category: 'frontend',
		difficulty: 'normal',
		file: 'Tailwind-CSS.png',
		description: '유틸리티 퍼스트 CSS 프레임워크. 클래스 조합만으로 디자인을 완성합니다.',
		distractors: ['Bootstrap', 'Bulma', 'Sass'],
	},

	// ─── Hard ────────────────────────────────────────────────────
	{
		id: 'logo_solidjs',
		name: 'Solid.js',
		category: 'frontend',
		difficulty: 'hard',
		file: 'Solid.js.png',
		description: '세밀한 반응성(Fine-grained reactivity)을 가진 UI 라이브러리. React와 비슷하지만 더 빠릅니다.',
		distractors: ['React', 'Svelte', 'Preact'],
	},
	{
		id: 'logo_qwik',
		name: 'Qwik',
		category: 'frontend',
		difficulty: 'hard',
		file: 'Qwik.png',
		description: 'Resumability 개념으로 HTML 직렬화를 통해 빠른 초기 로딩을 달성하는 프레임워크입니다.',
		distractors: ['Astro', 'Svelte', 'Solid.js'],
	},
	{
		id: 'logo_astro',
		name: 'Astro',
		category: 'frontend',
		difficulty: 'hard',
		file: 'Astro.png',
		description: 'Island Architecture를 사용해 콘텐츠 중심 사이트에 최적화된 프레임워크입니다.',
		distractors: ['Next.js', 'Gatsby', 'Nuxt.js'],
	},
	{
		id: 'logo_alpinejs',
		name: 'Alpine.js',
		category: 'frontend',
		difficulty: 'hard',
		file: 'Alpine.js.png',
		description: '최소한의 JS로 인터랙티비티를 추가하는 경량 프레임워크. jQuery 대안으로 자주 쓰입니다.',
		distractors: ['Vue.js', 'Stimulus.js', 'Petite-vue'],
	},

	// ══════════════════════════════════════════════════════════════
	// ⚙️ BACKEND
	// ══════════════════════════════════════════════════════════════

	// ─── Easy ───────────────────────────────────────────────────
	{
		id: 'logo_django',
		name: 'Django',
		category: 'backend',
		difficulty: 'easy',
		file: 'Django.png',
		description: 'Python 기반 풀스택 웹 프레임워크. "Batteries included" 철학으로 모든 기능이 내장됩니다.',
		distractors: ['Flask', 'FastAPI', 'Ruby on Rails'],
	},
	{
		id: 'logo_spring',
		name: 'Spring',
		category: 'backend',
		difficulty: 'easy',
		file: 'Spring.png',
		description: 'Java/Kotlin 기반 엔터프라이즈 프레임워크. DI와 AOP를 핵심으로 합니다.',
		distractors: ['Quarkus', 'Micronaut', 'Ktor'],
	},
	{
		id: 'logo_express',
		name: 'Express',
		category: 'backend',
		difficulty: 'easy',
		file: 'Express.png',
		description: 'Node.js 생태계에서 가장 많이 쓰이는 미니멀 웹 프레임워크입니다.',
		distractors: ['Fastify', 'Nest.js', 'Koa.js'],
	},
	{
		id: 'logo_laravel',
		name: 'Laravel',
		category: 'backend',
		difficulty: 'easy',
		file: 'Laravel.png',
		description: 'PHP 생태계의 대표 풀스택 프레임워크. Eloquent ORM과 Blade 템플릿이 특징입니다.',
		distractors: ['Symfony', 'CodeIgniter', 'CakePHP'],
	},

	// ─── Normal ─────────────────────────────────────────────────
	{
		id: 'logo_fastapi',
		name: 'FastAPI',
		category: 'backend',
		difficulty: 'normal',
		file: 'FastAPI.png',
		description: 'Python 타입 힌트 기반의 고성능 API 프레임워크. 자동 OpenAPI 문서 생성이 특징입니다.',
		distractors: ['Django', 'Flask', 'Falcon'],
	},
	{
		id: 'logo_nestjs',
		name: 'Nest.js',
		category: 'backend',
		difficulty: 'normal',
		file: 'Nest.js.png',
		description: 'TypeScript 기반 Node.js 프레임워크. Angular에서 영감을 받아 모듈/서비스/컨트롤러 구조를 사용합니다.',
		distractors: ['Express', 'Fastify', 'Koa.js'],
	},
	{
		id: 'logo_flask',
		name: 'Flask',
		category: 'backend',
		difficulty: 'normal',
		file: 'Flask.png',
		description: 'Python 기반 마이크로 웹 프레임워크. 필요한 것만 추가하는 미니멀 설계입니다.',
		distractors: ['Django', 'FastAPI', 'Tornado'],
	},
	{
		id: 'logo_fastify',
		name: 'Fastify',
		category: 'backend',
		difficulty: 'normal',
		file: 'Fastify.png',
		description: 'Node.js에서 가장 빠른 웹 프레임워크 중 하나. JSON 스키마 기반 직렬화가 특징입니다.',
		distractors: ['Express', 'Nest.js', 'Hapi.js'],
	},
	{
		id: 'logo_symfony',
		name: 'Symfony',
		category: 'backend',
		difficulty: 'normal',
		file: 'Symfony.png',
		description: 'PHP 기반 컴포넌트 프레임워크. Laravel을 포함한 많은 프레임워크가 Symfony 컴포넌트를 사용합니다.',
		distractors: ['Laravel', 'CodeIgniter', 'Zend Framework'],
	},
	{
		id: 'logo_graphql',
		name: 'GraphQL',
		category: 'backend',
		difficulty: 'normal',
		file: 'GraphQL.png',
		description: 'Facebook이 개발한 API 쿼리 언어. 클라이언트가 필요한 데이터만 정확히 요청할 수 있습니다.',
		distractors: ['REST', 'gRPC', 'tRPC'],
	},

	// ─── Hard ────────────────────────────────────────────────────
	{
		id: 'logo_quarkus',
		name: 'Quarkus',
		category: 'backend',
		difficulty: 'hard',
		file: 'Quarkus.png',
		description: 'Kubernetes 네이티브 Java 프레임워크. GraalVM 네이티브 이미지로 초고속 부팅이 가능합니다.',
		distractors: ['Spring', 'Micronaut', 'Ktor'],
	},
	{
		id: 'logo_ktor',
		name: 'Ktor',
		category: 'backend',
		difficulty: 'hard',
		file: 'Ktor.png',
		description: 'JetBrains가 만든 Kotlin 기반 비동기 웹 프레임워크. 코루틴을 적극 활용합니다.',
		distractors: ['Spring', 'Quarkus', 'Micronaut'],
	},
	{
		id: 'logo_adonisjs',
		name: 'AdonisJS',
		category: 'backend',
		difficulty: 'hard',
		file: 'AdonisJS.png',
		description: 'Node.js 생태계의 풀스택 MVC 프레임워크. Laravel에서 영감을 받아 만들어졌습니다.',
		distractors: ['Express', 'Nest.js', 'Fastify'],
	},
	{
		id: 'logo_feathers',
		name: 'Feathers',
		category: 'backend',
		difficulty: 'hard',
		file: 'Feathers.png',
		description: 'REST와 실시간 API를 동시에 구축할 수 있는 Node.js 프레임워크입니다.',
		distractors: ['Express', 'Socket.io', 'Hapi.js'],
	},

	// ══════════════════════════════════════════════════════════════
	// 🐳 DEVOPS / CLOUD
	// ══════════════════════════════════════════════════════════════

	// ─── Easy ───────────────────────────────────────────────────
	{
		id: 'logo_docker',
		name: 'Docker',
		category: 'devops',
		difficulty: 'easy',
		file: 'Docker.png',
		description: '컨테이너 기술의 대명사. 애플리케이션을 어디서나 동일하게 실행할 수 있게 패키징합니다.',
		distractors: ['Podman', 'Containerd', 'LXC'],
	},
	{
		id: 'logo_github',
		name: 'GitHub',
		category: 'devops',
		difficulty: 'easy',
		file: 'GitHub.png',
		description: 'Microsoft 소유의 Git 저장소 호스팅 플랫폼. 세계 최대 오픈소스 커뮤니티입니다.',
		distractors: ['GitLab', 'Bitbucket', 'Gitea'],
	},
	{
		id: 'logo_aws',
		name: 'AWS',
		category: 'devops',
		difficulty: 'easy',
		file: 'AWS.png',
		description: 'Amazon Web Services. 세계 최대의 클라우드 플랫폼으로 200개 이상의 서비스를 제공합니다.',
		distractors: ['Azure', 'Google Cloud', 'DigitalOcean'],
	},
	{
		id: 'logo_azure',
		name: 'Azure',
		category: 'devops',
		difficulty: 'easy',
		file: 'Azure.png',
		description: 'Microsoft의 클라우드 플랫폼. 엔터프라이즈 환경과 .NET 생태계에 강점이 있습니다.',
		distractors: ['AWS', 'Google Cloud', 'Oracle Cloud'],
	},

	// ─── Normal ─────────────────────────────────────────────────
	{
		id: 'logo_kubernetes',
		name: 'Kubernetes',
		category: 'devops',
		difficulty: 'normal',
		file: 'Kubernetes.png',
		description: 'Google이 오픈소스로 공개한 컨테이너 오케스트레이션 플랫폼입니다.',
		distractors: ['Docker Swarm', 'Nomad', 'Rancher'],
	},
	{
		id: 'logo_terraform',
		name: 'Terraform',
		category: 'devops',
		difficulty: 'normal',
		file: 'HashiCorp-Terraform.png',
		description: 'HashiCorp가 만든 Infrastructure as Code(IaC) 도구. HCL 언어로 인프라를 선언합니다.',
		distractors: ['Ansible', 'Pulumi', 'CloudFormation'],
	},
	{
		id: 'logo_jenkins',
		name: 'Jenkins',
		category: 'devops',
		difficulty: 'normal',
		file: 'Jenkins.png',
		description: '가장 오래되고 널리 쓰이는 오픈소스 CI/CD 자동화 서버입니다.',
		distractors: ['CircleCI', 'Travis CI', 'TeamCity'],
	},
	{
		id: 'logo_github_actions',
		name: 'GitHub Actions',
		category: 'devops',
		difficulty: 'normal',
		file: 'GitHub-Actions.png',
		description: 'GitHub에 내장된 CI/CD 플랫폼. YAML 워크플로우로 자동화를 정의합니다.',
		distractors: ['Jenkins', 'CircleCI', 'GitLab CI'],
	},
	{
		id: 'logo_ansible',
		name: 'Ansible',
		category: 'devops',
		difficulty: 'normal',
		file: 'Ansible.png',
		description: 'Red Hat의 에이전트리스 IT 자동화 도구. YAML 플레이북으로 서버를 구성합니다.',
		distractors: ['Terraform', 'Chef', 'Puppet'],
	},
	{
		id: 'logo_circleci',
		name: 'CircleCI',
		category: 'devops',
		difficulty: 'normal',
		file: 'CircleCI.png',
		description: '클라우드 기반 CI/CD 플랫폼. 빠른 파이프라인 실행과 Docker 기반 환경이 특징입니다.',
		distractors: ['Jenkins', 'Travis CI', 'GitHub Actions'],
	},

	// ─── Hard ────────────────────────────────────────────────────
	{
		id: 'logo_argocd',
		name: 'Argo CD',
		category: 'devops',
		difficulty: 'hard',
		file: 'Argo-CD.png',
		description: 'GitOps 방식의 Kubernetes 지속적 배포 도구. Git 상태와 클러스터 상태를 동기화합니다.',
		distractors: ['Flux', 'Spinnaker', 'Jenkins X'],
	},
	{
		id: 'logo_traefik',
		name: 'Traefik',
		category: 'devops',
		difficulty: 'hard',
		file: 'Traefik-Proxy.png',
		description: 'Go로 작성된 클라우드 네이티브 리버스 프록시. Docker/K8s 환경에서 자동 서비스 디스커버리를 지원합니다.',
		distractors: ['Nginx', 'HAProxy', 'Envoy'],
	},
	{
		id: 'logo_helm',
		name: 'Helm',
		category: 'devops',
		difficulty: 'hard',
		file: 'Helm.png',
		description: 'Kubernetes의 패키지 매니저. Chart라는 형식으로 앱 배포를 표준화합니다.',
		distractors: ['Kustomize', 'Skaffold', 'Flux'],
	},
	{
		id: 'logo_prometheus',
		name: 'Prometheus',
		category: 'devops',
		difficulty: 'hard',
		file: 'Prometheus.png',
		description: 'SoundCloud에서 시작된 오픈소스 모니터링 시스템. PromQL로 메트릭을 쿼리합니다.',
		distractors: ['Grafana', 'InfluxDB', 'Zabbix'],
	},
	{
		id: 'logo_grafana',
		name: 'Grafana',
		category: 'devops',
		difficulty: 'hard',
		file: 'Grafana.png',
		description: '시계열 데이터 시각화 플랫폼. Prometheus, InfluxDB 등 다양한 데이터소스를 지원합니다.',
		distractors: ['Prometheus', 'Kibana', 'Datadog'],
	},

	// ══════════════════════════════════════════════════════════════
	// 🗄️ DB / INFRASTRUCTURE
	// ══════════════════════════════════════════════════════════════

	// ─── Easy ───────────────────────────────────────────────────
	{
		id: 'logo_mysql',
		name: 'MySQL',
		category: 'db',
		difficulty: 'easy',
		file: 'MySQL.png',
		description: '세계에서 가장 많이 쓰이는 오픈소스 관계형 데이터베이스. Oracle이 소유하고 있습니다.',
		distractors: ['PostgreSQL', 'MariaDB', 'SQLite'],
	},
	{
		id: 'logo_mongodb',
		name: 'MongoDB',
		category: 'db',
		difficulty: 'easy',
		file: 'MongoDB.png',
		description: '가장 인기 있는 NoSQL 도큐먼트 데이터베이스. JSON 형식으로 데이터를 저장합니다.',
		distractors: ['CouchDB', 'Cassandra', 'Redis'],
	},
	{
		id: 'logo_redis',
		name: 'Redis',
		category: 'db',
		difficulty: 'easy',
		file: 'Redis.png',
		description: '인메모리 키-값 저장소. 캐시, 세션, 실시간 랭킹 등에 널리 사용됩니다.',
		distractors: ['Memcached', 'Hazelcast', 'MongoDB'],
	},
	{
		id: 'logo_sqlite',
		name: 'SQLite',
		category: 'db',
		difficulty: 'easy',
		file: 'SQLite.png',
		description: '서버 없이 파일 하나로 동작하는 경량 관계형 DB. 모바일과 임베디드 환경에 적합합니다.',
		distractors: ['MySQL', 'PostgreSQL', 'DuckDB'],
	},

	// ─── Normal ─────────────────────────────────────────────────
	{
		id: 'logo_postgresql',
		name: 'PostgreSQL',
		category: 'db',
		difficulty: 'normal',
		file: 'PostgresSQL.png',
		description: '고급 SQL 기능과 JSONB, PostGIS 등 확장성이 뛰어난 오픈소스 관계형 DB입니다.',
		distractors: ['MySQL', 'MariaDB', 'CockroachDB'],
	},
	{
		id: 'logo_kafka',
		name: 'Apache Kafka',
		category: 'db',
		difficulty: 'normal',
		file: 'Apache-Kafka.png',
		description: 'LinkedIn이 만든 분산 이벤트 스트리밍 플랫폼. 초당 수백만 건의 메시지를 처리합니다.',
		distractors: ['RabbitMQ', 'ActiveMQ', 'NATS'],
	},
	{
		id: 'logo_elasticsearch',
		name: 'Elasticsearch',
		category: 'db',
		difficulty: 'normal',
		file: 'Elastic-Search.png',
		description: 'Elastic이 만든 분산 검색 및 분석 엔진. 전문 검색과 로그 분석에 주로 사용됩니다.',
		distractors: ['Solr', 'Opensearch', 'Typesense'],
	},
	{
		id: 'logo_rabbitmq',
		name: 'RabbitMQ',
		category: 'db',
		difficulty: 'normal',
		file: 'RabbitMQ.png',
		description: 'AMQP 프로토콜 기반의 오픈소스 메시지 브로커. Exchange와 Queue 개념이 핵심입니다.',
		distractors: ['Kafka', 'ActiveMQ', 'NATS'],
	},
	{
		id: 'logo_influxdb',
		name: 'InfluxDB',
		category: 'db',
		difficulty: 'normal',
		file: 'InfluxDB.png',
		description: '시계열 데이터 전용 데이터베이스. IoT, 모니터링, 실시간 분석에 최적화되어 있습니다.',
		distractors: ['Prometheus', 'TimescaleDB', 'Graphite'],
	},
	{
		id: 'logo_firebase',
		name: 'Firebase',
		category: 'db',
		difficulty: 'normal',
		file: 'Firebase.png',
		description: 'Google의 모바일/웹 개발 플랫폼. 실시간 데이터베이스, 인증, 호스팅을 한 번에 제공합니다.',
		distractors: ['Supabase', 'Appwrite', 'PocketBase'],
	},

	// ─── Hard ────────────────────────────────────────────────────
	{
		id: 'logo_couchdb',
		name: 'CouchDB',
		category: 'db',
		difficulty: 'hard',
		file: 'CouchDB.png',
		description: 'Apache의 HTTP API 기반 도큐먼트 DB. 오프라인 우선 동기화와 MVCC가 특징입니다.',
		distractors: ['MongoDB', 'Couchbase', 'RethinkDB'],
	},
	{
		id: 'logo_cassandra',
		name: 'Apache Cassandra',
		category: 'db',
		difficulty: 'hard',
		file: 'Apache-Cassandra.png',
		description: 'Facebook이 개발한 분산 NoSQL DB. 단일 장애점 없이 선형 확장이 가능합니다.',
		distractors: ['HBase', 'ScyllaDB', 'DynamoDB'],
	},
	{
		id: 'logo_rocksdb',
		name: 'RocksDB',
		category: 'db',
		difficulty: 'hard',
		file: 'RocksDB.png',
		description: 'Facebook이 LevelDB를 포크하여 만든 임베디드 키-값 스토어. TiKV, CockroachDB의 기반입니다.',
		distractors: ['LevelDB', 'BadgerDB', 'TiKV'],
	},
	{
		id: 'logo_cosmos',
		name: 'Cosmos DB',
		category: 'db',
		difficulty: 'hard',
		file: 'Cosmos-BD.png',
		description: 'Microsoft Azure의 글로벌 분산 멀티모델 DB. 99.999% SLA와 ms 단위 응답을 보장합니다.',
		distractors: ['DynamoDB', 'Firestore', 'Bigtable'],
	},
];

module.exports = { LOGOS };
